# Generated by Django 4.1.6 on 2023-05-31 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=50)),
                ('SecondName', models.TextField(max_length=50)),
                ('FirstSurname', models.TextField(max_length=50)),
                ('SecondSurname', models.TextField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('Sex', models.CharField(max_length=1)),
                ('Address', models.TextField()),
                ('Origin', models.CharField(max_length=2)),
                ('Phone', models.TextField(max_length=8)),
                ('Email', models.EmailField(max_length=254)),
                ('MaritalStatus', models.CharField(max_length=1)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Treatment', models.TextField()),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=50)),
                ('SecondName', models.TextField(max_length=50)),
                ('FirstSurname', models.TextField(max_length=50)),
                ('SecondSurname', models.TextField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('Sex', models.CharField(max_length=1)),
                ('Address', models.TextField()),
                ('Origin', models.CharField(max_length=2)),
                ('Phone', models.TextField(max_length=8)),
                ('Email', models.EmailField(max_length=254)),
                ('MaritalStatus', models.CharField(max_length=1)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('State', models.CharField(default='1', max_length=1)),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=50)),
                ('SecondName', models.TextField(max_length=50)),
                ('FirstSurname', models.TextField(max_length=50)),
                ('SecondSurname', models.TextField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('Sex', models.CharField(max_length=1)),
                ('Address', models.TextField()),
                ('Origin', models.CharField(max_length=2)),
                ('Phone', models.TextField(max_length=8)),
                ('Email', models.EmailField(max_length=254)),
                ('Occupation', models.TextField(max_length=50)),
                ('MaritalStatus', models.CharField(max_length=1)),
                ('EmergencyCase', models.TextField(max_length=50)),
                ('EmergencyNumber', models.TextField(max_length=8)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('idDoctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('idPatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
                ('idPersonal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.assistant')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idMainBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.budgetfields')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Done', models.BooleanField(default=False)),
                ('idMainBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.mainbudget')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alergias', models.CharField(max_length=1)),
                ('Patologicos', models.CharField(max_length=1)),
                ('Farmacologicos', models.CharField(max_length=1)),
                ('Hospitalizaciones', models.CharField(max_length=1)),
                ('Quirurgico', models.CharField(max_length=1)),
                ('Transfusiones', models.CharField(max_length=1)),
                ('Radioterapia', models.CharField(max_length=1)),
                ('Quimioterapia', models.CharField(max_length=1)),
                ('Habitos', models.CharField(max_length=1)),
                ('COVID', models.CharField(max_length=1)),
                ('CantidadDosis', models.IntegerField(blank=True, null=True)),
                ('UltimaDosis', models.DateField(blank=True, null=True)),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('VisitaFrecuente', models.CharField(max_length=1)),
                ('FechaUltimaVisita', models.DateField(blank=True, null=True)),
                ('HiloDental', models.CharField(max_length=1)),
                ('Enjuague', models.CharField(max_length=1)),
                ('Experiencia', models.CharField(blank=True, max_length=1, null=True)),
                ('TipoCepillo', models.CharField(max_length=1)),
                ('FrecuenciaDeCepillado', models.CharField(max_length=1)),
                ('FrecuenciaDeHilo', models.CharField(blank=True, max_length=1, null=True)),
                ('Otros', models.TextField(blank=True, null=True)),
                ('Periodoncia', models.BooleanField(default=False)),
                ('Endodoncia', models.BooleanField(default=False)),
                ('Exodoncia', models.BooleanField(default=False)),
                ('ImplanteDental', models.BooleanField(default=False)),
                ('Protesis', models.BooleanField(default=False)),
                ('OperatoriaDental', models.BooleanField(default=False)),
                ('CirugiaOral', models.BooleanField(default=False)),
                ('Ortodoncia', models.BooleanField(default=False)),
                ('Diagnostico', models.BooleanField(default=False)),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
        ),
        migrations.AddField(
            model_name='mainbudget',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient'),
        ),
        migrations.AddField(
            model_name='budgetfields',
            name='idMainBudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.mainbudget'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(default='1', max_length=1)),
                ('idDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient')),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
    ]
